### ISSUE TITLE
Exception "failed to map segment from shared object" when running AppImage on Linux Manjaro 18.1.5

### ISSUE THREAD

**Issue by pavelsaman** [firecampapp/Firecamp#48]
1. problem

When opening the app, I get the following exception, and the app never opens up so I can interact with it:

```
A JavaScript error occurred in the main process
Uncaught Exception:
Error: /tmp/.org.chromium.Chromium.SxerlG: failed to map segment from shared object
    at process.func (electron/js2c/asar.js:140:31)
    at process.func [as dlopen] (electron/js2c/asar.js:140:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:922:18)
    at Object.func (electron/js2c/asar.js:140:31)
    at Object.func [as .node] (electron/js2c/asar.js:149:18)
    at Module.load (internal/modules/cjs/loader.js:735:32)
    at Module._load (internal/modules/cjs/loader.js:648:12)
    at Module._load (electron/js2c/asar.js:717:26)
    at Function.Module._load (electron/js2c/asar.js:717:26)
    at Module.require (internal/modules/cjs/loader.js:775:19)
```
I'm not completely sure if my platform is/should be supported, but since I'm trying to run an AppImage on a new and fully updated system, I don't see a reason why this should end up in an exception.

2. how to reproduce

Set up the platform I have (see below) => chmod u+x Firecamp-0.9.2.AppImage => $ Firecamp-0.9.2.AppImage

3. version
0.9.2, AppImage downloaded from here: https://firecamp.ams3.digitaloceanspaces.com/versions/linux/Firecamp-0.9.2.AppImage

4. platform
Manjaro 18.1.5 with Xfce, x64, kernel 4.19.97-1

**Comment by Nishchit14** [comment]
Thanks for sharing the details @pavelsaman . I'll try to reproduce it at my end.

can you please also try it with a snap command `snap install firecamp`?

**Comment by pavelsaman** [comment]
@Nishchit14 
Using snap:
```
$ snap --version
snap     2.43.1-1
snapd    2.43.1-1
series   16
manjaro  -
kernel   4.19.98-1-MANJARO
```
firecamp starts up ok and seems just fine. So it seems there's only a problem with the AppImage format.

(And my kernel is a bit newer now (4.19.98-1).)

**Comment by Nishchit14** [comment]
The issue was  `AppImage` got corrupted while uploading to the download server. You can now download the same `v0.9.2` and It would work fine.  Thanks for driving our attention to this issue 🙌

**Comment by pavelsaman** [comment]
I face th same issue even now. The same version of firecamp downloaded from https://firecamp.ams3.digitaloceanspaces.com/versions/linux/Firecamp-0.9.2.AppImage 

It doesn't seem to be resolved.

**Comment by Nishchit14** [comment]
Tested new AppImage 0.9.2 with Linux Mint, Ubuntu and It's working fine. Need to test with Manjaro Linux.

**Comment by pavelsaman** [comment]
Sure, it might be a problem with something specific in my configuration. If you need more information, let me know.

**Comment by Nishchit14** [comment]
Thanks @pavelsaman 
Please join our newly discord community https://discord.gg/8hRaqhK, It would be great if we can connect so reproduce the same issue again.
